"""Added ticket escalation date

Revision ID: 364cabb993d9
Revises: d0deecf90187
Create Date: 2026-07-11 19:58:02.254534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '364cabb993d9'
down_revision = 'd0deecf90187'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('escalated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'escalated_at')
    # ### end Alembic commands ###
