"""Added escalation level

Revision ID: 54470447f575
Revises: 364cabb993d9
Create Date: 2026-07-11 21:11:58.688991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54470447f575'
down_revision = '364cabb993d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
    'tickets',
    sa.Column(
        'escalation_level',
        sa.Integer(),
        nullable=False,
        server_default='0'
    )
)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'escalation_level')
    # ### end Alembic commands ###
