"""Added SLA due date

Revision ID: 6a0255acd04b
Revises: 4b123caa279f
Create Date: 2026-07-11 18:22:23.786873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a0255acd04b'
down_revision = '4b123caa279f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('sla_due_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'sla_due_at')
    # ### end Alembic commands ###
