"""Added ticket resolved date

Revision ID: d0deecf90187
Revises: 6a0255acd04b
Create Date: 2026-07-11 19:10:23.475170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0deecf90187'
down_revision = '6a0255acd04b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('resolved_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'resolved_at')
    # ### end Alembic commands ###
